### ISSUE TITLE
Action proposal: Lightweight/Minimalistic Show Notification 

### ISSUE THREAD

**Issue by FelipeRearden** [sindresorhus/Actions#257] opened 2024-07-11 16:13 UTC
### Description

Hello @sindresorhus 

When you have more than 600 shortcuts like me you have to develop a system based on names, colors and symbols to organize the shortcuts inside the folders. 

This way, many shortcuts got long names and colors that are not very good.

The effect is that when I use the native shortcut action `Show Notification` it gets the long name of the shortcut and the color that dont like. 

This way, my Action Proposal a new Notififcation that is simple, and customizable. 

By simple, and customizable I mean: if you could that the same components of the amazing action `Create Meu Item`
- Title 
- Subtitle
- SF Symbol 🙏

And apply to a new Notification action, would amazing to create a notification that is customizable and beautiful.

<hr>

Thanks, let me know if you need more details.

**Comment by sindresorhus** [comment] 2024-09-23 19:04
Duplicate of #97

**Comment by sindresorhus** [comment] 2024-09-23 19:04
This is now available in the latest TestFlight build: https://testflight.apple.com/join/fJGUrsZx And will be available in the next App Store update.

**Closed by sindresorhus** 2024-09-23 19:04 UTC
Labels: new action
