### ISSUE TITLE
Action proposal: Local Notifications

### ISSUE THREAD

**Issue by NoahKamara** [sindresorhus/Actions#142] opened 2023-08-22 14:42 UTC
### Description

- The shortcut app allows users to send a notification but not to specify an URL to open when the notification is tapped

The action could look like this:
Send Notification with `title` and `optional subtitle`
- body
- date
- thread ID (string - allows grouping in notification center - possible alternate name 'groupID')
- tap-url

I'd be happy to implement this if accepted

**Comment by sindresorhus** [comment] 2023-08-22 16:29
Accepted 👍

**Comment by PyaePhyo8612** [comment] 2023-09-29 09:55
Backup code

**Comment by sindresorhus** [comment] 2024-09-23 19:03
Duplicate of #97

**Comment by sindresorhus** [comment] 2024-09-23 19:03
This is now available in the latest TestFlight build: https://testflight.apple.com/join/fJGUrsZx And will be available in the next App Store update.

**Closed by sindresorhus** 2024-09-23 19:03 UTC
Labels: help wanted, new action
